language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2.2.1
matrix:
  allow_failures:
      - rvm: rbx-2.2.1
before_install:
  - git submodule update --init --recursive
env:
  - MAX=true BLAH=bar
after_script:
  - touch tmp/challenge_opts
  - . tmp/challenge_opts
  - bundle exec rake challenge
