language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
env:
  JSON_GENERATOR="bundle exec json_schema_generator"
before_install:
  - git submodule update --init --recursive
  - cd tests && bundle install
